const ADD_LOGIN = "ADD_LOGIN";
const LOGIN_LOADING = "LOGIN_LOADING";
const LOGIN_FAILED = "LOGIN_FAILED";
const REMOVE_LOGIN = "REMOVE_LOGIN";
const SET_VIEW_MODE = "SET_VIEW_MODE";
const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
const RENEW_ACCESS_TOKEN = "RENEW_ACCESS_TOKEN";

// logs
const SET_DEV_SERVER_LOG = "SET_DEV_SERVER_LOG";
const SET_PROD_SERVER_LOG = "SET_PROD_SERVER_LOG";
const CLEAR_DEV_SERVER_LOG = "CLEAR_DEV_SERVER_LOG";
const CLEAR_PROD_SERVER_LOG = "CLEAR_PROD_SERVER_LOG";

const ActionTypes = {
	ADD_LOGIN,
	REMOVE_LOGIN,

    // tokens
    SET_ACCESS_TOKEN,
    SET_REFRESH_TOKEN,
    RENEW_ACCESS_TOKEN,
};

export default ActionTypes;
